server:
  servlet:
    context-path: /api

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    url: jdbc:mysql://localhost:3306/beerClub
    username: admin
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  properties:
    hibernate.format_sql: true